apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8001
    insecure-skip-tls-verify: true
  name: local-k3s
contexts:
- context:
    cluster: local-k3s
    user: local-user
  name: local-k3s
current-context: local-k3s
kind: Config
preferences: {}
users:
- name: local-user
  user: {}
